"""empty message

Revision ID: 1c06b5f8e66d
Revises: 07bf2cd01b16
Create Date: 2020-04-26 00:38:44.831579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c06b5f8e66d"
down_revision = "07bf2cd01b16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "posts", "scenes", ["scene"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_table("scenes")
    # ### end Alembic commands ###
