"""empty message

Revision ID: 6cbf800bfa32
Revises: 83e459e0e677
Create Date: 2020-04-26 21:52:25.988407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbf800bfa32'
down_revision = '83e459e0e677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_filename')
    # ### end Alembic commands ###
