"""empty message

Revision ID: a8c861ea0380
Revises: 2290731c1bbf
Create Date: 2020-04-26 02:35:31.360564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8c861ea0380"
down_revision = "2290731c1bbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scenes", sa.Column("category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenes", "category")
    # ### end Alembic commands ###
