"""empty message

Revision ID: d29ac02e0bae
Revises: 93c8dea4632e
Create Date: 2020-04-30 19:33:25.621097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d29ac02e0bae"
down_revision = "93c8dea4632e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scenes", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenes", "description")
    # ### end Alembic commands ###
