"""empty message

Revision ID: fce1e45925d8
Revises: 1c06b5f8e66d
Create Date: 2020-04-26 01:05:10.550239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce1e45925d8'
down_revision = '1c06b5f8e66d'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_test_timestamp'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
